import { supabase } from './supabase'
import type { ConversationMessage, ConversationSummary } from './lsc2-api'
export type ConversationSummaryV11=ConversationSummary&{peer_character_id:string|null;is_favorite:boolean;is_contact:boolean;presence_state:'online'|'away'|'offline'|null;last_seen_at:string|null;can_message:boolean;peer_deleted:boolean}
export type ConversationMessageV11=ConversationMessage&{author_avatar_url:string|null;read_state:'sent'|'partially_read'|'read'|null;read_at:string|null;reader_count:number;recipient_count:number}
function fail(label:string,error:{message?:string}|null){return new Error(error?.message?label+': '+error.message:label)}
function normalizeThreads(data:unknown):ConversationSummaryV11[]{return((Array.isArray(data)?data:[])as ConversationSummaryV11[]).map(r=>({...r,unread_count:Number(r.unread_count??0),member_count:Number(r.member_count??0),is_favorite:r.is_favorite===true,is_contact:r.is_contact===true,can_message:r.can_message!==false,peer_deleted:r.peer_deleted===true}))}
export async function listMyConversationsV11():Promise<ConversationSummaryV11[]>{const{data,error}=await supabase.rpc('lsc2_my_conversations_v4',{p_mode:'active'});if(error)throw fail('Chats konnten nicht geladen werden',error);return normalizeThreads(data)}
export async function listArchivedConversationsV12():Promise<ConversationSummaryV11[]>{const{data,error}=await supabase.rpc('lsc2_my_conversations_v4',{p_mode:'archived'});if(error)throw fail('Archivierte Chats konnten nicht geladen werden',error);return normalizeThreads(data)}
export async function listConversationMessagesV11(id:string,limit=100):Promise<ConversationMessageV11[]>{const{data,error}=await supabase.rpc('lsc2_conversation_messages_v5',{p_conversation_id:id,p_limit:limit});if(error)throw fail('Nachrichten konnten nicht geladen werden',error);return((Array.isArray(data)?data:[])as ConversationMessageV11[]).map(r=>({...r,reader_count:Number(r.reader_count??0),recipient_count:Number(r.recipient_count??0),reactions:Array.isArray(r.reactions)?r.reactions.map(x=>({...x,count:Number(x.count??0)})):[],attachments:Array.isArray(r.attachments)?r.attachments:[]}))}
export async function setConversationFavoriteV11(id:string,favorite:boolean){const{data,error}=await supabase.rpc('lsc2_set_conversation_favorite',{p_conversation_id:id,p_favorite:favorite});if(error)throw fail('Favorit konnte nicht geändert werden',error);return data===true}
export async function setConversationArchivedV12(id:string,archived:boolean){const{data,error}=await supabase.rpc('lsc2_set_conversation_archived',{p_conversation_id:id,p_archived:archived});if(error)throw fail(archived?'Chat konnte nicht archiviert werden':'Chat konnte nicht wiederhergestellt werden',error);return data===true}
export async function deleteConversationForMeV12(id:string){const{error}=await supabase.rpc('lsc2_delete_conversation_for_me',{p_conversation_id:id});if(error)throw fail('Chat konnte nicht endgültig gelöscht werden',error)}
