import{readFileSync,writeFileSync,existsSync}from'node:fs';
function rep(p,a,b,l){const s=readFileSync(p,'utf8');if(!s.includes(a))throw Error('missing '+l);writeFileSync(p,s.replace(a,b))}
function inclusive(p,a,b,v,l){const s=readFileSync(p,'utf8'),i=s.indexOf(a),j=s.indexOf(b,i+a.length);if(i<0||j<0)throw Error('missing '+l+' '+i+' '+j);writeFileSync(p,s.slice(0,i)+v+s.slice(j+b.length))}
const m='src/features/messenger/MessengerHome.tsx';
rep('src/app/App.tsx','<div className="content-area">','<div className={section === \'messenger\' ? \'content-area content-area-messenger\' : \'content-area\'}>','content');
rep(m,"import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react'","import { Fragment, useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react'",'fragment');
rep(m,"import { CallOverlay } from './CallOverlay'","import { listConversationMessagesV11,listMyConversationsV11,setConversationFavoriteV11,type ConversationMessageV11,type ConversationSummaryV11 } from '../../lib/messenger-v11-api'\nimport { CallOverlay } from './CallOverlay'",'adapter');
rep(m,"const quickReactions = ['👍', '❤️', '😂']","const quickReactions=['👍','❤️','😂','🔥','👏']\nconst emojiPalette=['😀','😃','😄','😁','😂','🤣','😊','😍','🥰','😘','😎','🤔','😅','😢','😭','😡','🤯','🥳','😴','🤝','🙏','💪','👍','👎','👏','🙌','👀','❤️','🧡','💛','💚','💙','💜','🖤','🤍','💔','🔥','✨','⭐','🎉','🎯','✅','❌','⚠️','💯','🚀','📌','📣','🚓','🚑','🚒','🏢','💼','📱','💬','📷','🎥','🎵']",'emoji');
{let s=readFileSync(m,'utf8'),i=s.indexOf('function initials(value: string) {'),j=s.indexOf('\n}',i)+2;if(i<0||j<2)throw Error('initials');s=s.slice(0,j)+'\n'+readFileSync('helpers.txt','utf8')+s.slice(j);writeFileSync(m,s)}
rep(m,'useState<ConversationSummary[]>([])','useState<ConversationSummaryV11[]>([])','threadtype');
rep(m,'useState<ConversationMessage[]>([])','useState<ConversationMessageV11[]>([])','msgtype');
rep(m,"  const [reportTarget, setReportTarget] = useState<{ type: ReportTargetType; id: string; label: string } | null>(null)\n  const typingTimer = useRef<number | null>(null)\n  const fileInputRef = useRef<HTMLInputElement | null>(null)","  const [reportTarget, setReportTarget] = useState<{ type: ReportTargetType; id: string; label: string } | null>(null)\n  const [composerEmojiOpen,setComposerEmojiOpen]=useState(false)\n  const [reactionPickerMessageId,setReactionPickerMessageId]=useState<string|null>(null)\n  const [newMessageCount,setNewMessageCount]=useState(0)\n  const typingTimer=useRef<number|null>(null)\n  const fileInputRef=useRef<HTMLInputElement|null>(null)\n  const messageListRef=useRef<HTMLDivElement|null>(null)\n  const nearBottomRef=useRef(true)\n  const initialScrollConversationRef=useRef<string|null>(null)\n  const lastMessageIdRef=useRef<string|null>(null)",'state');
rep(m,'  const activeThread = useMemo(','  const chatThreads=useMemo(()=>threads.filter(t=>t.kind!==\'organization\'),[threads])\n  const activeThread = useMemo(','filter');
rep(m,'const next = await listMyConversations()','const next = await listMyConversationsV11()','threads');
rep(m,'return next[0]?.conversation_id ?? null',"return next.find(x=>x.kind!=='organization')?.conversation_id ?? null",'default');
rep(m,'const next = await listConversationMessages(conversationId)','const next = await listConversationMessagesV11(conversationId)','msgs');
{let s=readFileSync(m,'utf8');s=s.replace(/\n\s*await markConversationRead\(conversationId\)/,'');s=s.replace(/setError\(reason instanceof Error \? reason\.message : ('[^']*')\)/g,'setError(friendlyMessengerError(reason,$1))');writeFileSync(m,s)}
rep(m,'    void Promise.all([refreshMessages(activeId), refreshMembers(activeId), refreshTyping(activeId)])',"    initialScrollConversationRef.current=activeId\n    lastMessageIdRef.current=null\n    nearBottomRef.current=true\n    setNewMessageCount(0)\n    setComposerEmojiOpen(false)\n    setReactionPickerMessageId(null)\n    void Promise.all([refreshMessages(activeId), refreshMembers(activeId), refreshTyping(activeId)])",'reset');
rep(m,'  function updateDraft(value: string) {',readFileSync('scroll.txt','utf8')+'  function updateDraft(value: string) {','scroll');
rep(m,'COMMUNICATION · API v0.6.0','COMMUNICATION · API v1.1.0','version');
rep(m,'{threads.length === 0 ? <div className="empty-state">Noch keine LS-C-2.0-Chats.</div> : null}','{chatThreads.length === 0 ? <div className="empty-state">Noch keine Direkt- oder Gruppenchats.</div> : null}','empty');
inclusive(m,'<div className="conversation-identity">','              <div className="conversation-header-actions">',readFileSync('header.txt','utf8')+'<div className="conversation-header-actions">','header');
inclusive(m,'{threads.map((thread) => (','\n          ))}\n        </div>\n      </div>\n\n      <div className="conversation-pane">',readFileSync('thread.txt','utf8'),'threadmap');
rep(m,'            <div className="message-list">','            <div className="message-list" ref={messageListRef} onScroll={handleMessageScroll}>','msgref');
inclusive(m,'{messages.map((message) => (','\n              ))}\n            </div>\n\n            <div className="typing-line">',readFileSync('messages.txt','utf8'),'msgmap');
rep(m,'            <div className="composer">',"            {activeThread.kind==='direct'&&!activeThread.can_message?<div className=\"composer-blocked-hint\">{activeThread.peer_deleted?'Dieser Charakter ist nicht mehr verfügbar.':'Dieser Nutzer akzeptiert derzeit keine Nachrichten von dir.'}</div>:null}\n            <div className=\"composer\">",'blocked');
rep(m,'              <textarea\n                value={draft}',"              <span className=\"composer-emoji-wrap\"><button className=\"attachment-button\" type=\"button\" title=\"Emoji\" onClick={()=>setComposerEmojiOpen(v=>!v)}>☺</button>{composerEmojiOpen?<EmojiPicker onPick={appendEmoji}/>:null}</span>\n              <textarea\n                value={draft}",'composeremoji');
writeFileSync('src/styles/app.css',readFileSync('src/styles/app.css','utf8')+'\n'+readFileSync('v11.css','utf8')+'\n');
if(existsSync('src/config/runtime.ts')){let s=readFileSync('src/config/runtime.ts','utf8');s=s.replace(/1\.0\.0/g,'1.1.0');writeFileSync('src/config/runtime.ts',s)}
const pkg=JSON.parse(readFileSync('package.json','utf8'));pkg.version='1.1.0';writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n');
const f=readFileSync(m,'utf8');for(const x of ['listMyConversationsV11','chatThreads.map','messageListRef','message-date-separator','delivery-state','composer-emoji-wrap','thread-favorite','COMMUNICATION · API v1.1.0'])if(!f.includes(x))throw Error('marker '+x);
console.log('v1.1 patch markers OK')